version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pedidos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6380"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: pedidos
        DB_USER: postgres
        DB_PASSWORD: postgres

volumes:
  pgdata:
